apiVersion: v1
kind: Namespace
metadata:
  name: arti-ns-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: arti-pv
  namespace: arti-ns-1
  labels:
    content: arti
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/home/dudaji/work/artiference/yamls"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: arti-pvc
  namespace: arti-ns-1
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      content: arti
---
apiVersion: v1
kind: Service
metadata:
  name: default-subdomain
  namespace: arti-ns-1
spec:
  selector:
    name: arti-svc
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5001
    nodePort: 32353
---
apiVersion: v1
kind: Pod
metadata:
  name: arti-node-1
  namespace: arti-ns-1
  labels:
    name: arti-svc
spec:
  hostname: arti-node-1
  subdomain: default-subdomain
  containers:
  - image: fla2:v1
    name : arti-node-1
    command: ['/bin/sh', '-ec']
    args:
      - sleep infinity;
    ports:
    - containerPort: 5001
    volumeMounts:
    - name: arti
      mountPath: /root/app
  volumes:
  - name: arti
    persistentVolumeClaim:
      claimName: arti-pvc
---
apiVersion: v1
kind: Pod
metadata:
  name: arti-node-2
  namespace: arti-ns-1
  labels:
    name: arti-svc
spec:
  hostname: arti-node-2
  subdomain: default-subdomain
  containers:
  - image: fla2:v1
    name : arti-node-2
    command: ['/bin/sh', '-ec']
    args:
      - sleep infinity;
    ports:
    - containerPort: 5000
    volumeMounts:
    - name: arti
      mountPath: /root/app
  volumes:
  - name: arti
    persistentVolumeClaim:
      claimName: arti-pvc
